# Basic config
baseURL = "https://pagliacii.github.io/silent-lake/"
languageCode = "zh-cn"
title = "Jason's Blog"
theme = "hugo-bearberry"
copyright = "[Jason Huang](https://github.com/Pagliacii) © since 2023"
defaultContentLanguage = "zh"
timeout = "60s"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

enableEmoji = true
enableGitInfo = true

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
lineAnchors = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
tabWidth = 4
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.cjk]
enable = true
[markup.goldmark.renderer]
unsafe = true

[languages]
[languages.zh]
title = "୧ʕ •ᴥ•ʔ୨ Silent Lake"
languageName = "中文"
LanguageCode = "zh-CN"
contentDir = "content"
[languages.zh.params]
blogPath = "blog"
madeWith = "Made With [Bear Berry](https://github.com/Pagliacii/hugo-bearberry)"

[params]
title = "Jason's blog"
description = "Jason's Blog"
hideUntranslated = false
generateSocialCard = true

# The path to your favicon
favicon = "images/favicon.ico"
favicon16 = "images/favicon-16x16.png"
favicon32 = "images/favicon-32x32.png"
apple_touch_icon = "images/apple-touch-icon.png"
manifest = "images/site.webmanifest"
safari_pinned_tab = "images/safari-pinned-tab.svg"
msapplication_tilecolor = "#da532c"
msapplication_config = "images/browserconfig.xml"
theme_color = "#fff"

# For information about giscus, see https://giscus.app/
[params.giscus]
repoName = "Pagliacii/silent-lake"
repoID = "R_kgDOKgeurQ"
category = "Comments"
categoryID = "DIC_kwDOKgeurc4CaZsJ"
mapping = "og:title"
reactionsEnabled = true
emitMetadata = true
theme = "https://giscus.catppuccin.com/themes/latte.css"

[params.social]
twitter = "PagliaciiH"
github = "Pagliacii"

[params.author]
name = "Jason Huang"
email = "huangmianrui0310@gmail.com"

# Optimize the performance for kroki diagrams
[caches]
[caches.getresource]
dir = ":resourceDir"
maxAge = -1
